apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yf3iki02r-go
  janus-idp.io/tekton: yf3iki02r-go
  backstage.io/kubernetes-id: yf3iki02r-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yf3iki02r-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
